Repository prgrms-web-devcourse-final-project/WEB1_2_PitchingMate_BE, pull requests merged in 2024-12, with the labels that each got.

#48 MATE-51: [FEAT] 굿즈거래 판매글 판매완료 기능 구현
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/goods/controller/GoodsController.java
  src/main/java/com/example/mate/domain/goods/entity/GoodsPost.java
  src/main/java/com/example/mate/domain/goods/service/GoodsService.java
  src/test/java/com/example/mate/domain/goods/controller/GoodsControllerTest.java
  src/test/java/com/example/mate/domain/goods/integration/GoodsIntegrationTest.java
  src/test/java/com/example/mate/domain/goods/service/GoodsServiceTest.java
Labels: ✨ Feature, ✅ Test

#50 MATE-43 : [FEAT] 굿즈 판매기록 페이징 조회 구현
  src/main/java/com/example/mate/common/response/PageResponse.java
  src/main/java/com/example/mate/domain/goods/repository/GoodsPostRepository.java
  src/main/java/com/example/mate/domain/member/controller/FollowController.java
  src/main/java/com/example/mate/domain/member/controller/ProfileController.java
  src/main/java/com/example/mate/domain/member/dto/response/MyGoodsRecordResponse.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
Labels: ✨ Feature, ✅ Test

#49 MATE-31 : [FEAT] 직관 후기 작성 기능 구현
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/constant/Rating.java
  src/main/java/com/example/mate/domain/mate/controller/MateController.java
  src/main/java/com/example/mate/domain/mate/dto/request/MateReviewCreateRequest.java
  src/main/java/com/example/mate/domain/mate/dto/request/MateReviewRequest.java
  src/main/java/com/example/mate/domain/mate/dto/response/MateReviewCreateResponse.java
  src/main/java/com/example/mate/domain/mate/entity/Age.java
  src/main/java/com/example/mate/domain/mate/entity/MateReview.java
  src/main/java/com/example/mate/domain/mate/entity/Visit.java
  src/main/java/com/example/mate/domain/mate/service/MateService.java
  src/test/java/com/example/mate/domain/mate/controller/MateReviewControllerTest.java
  src/test/java/com/example/mate/domain/mate/service/MateReviewServiceTest.java
  src/test/java/com/example/mate/domain/mate/service/MateStatusServiceTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
Labels: ✨ Feature, ✅ Test

#51 MATE-44 : [FEAT] 굿즈 구매기록 페이징 조회 구현
  src/main/java/com/example/mate/common/config/SecurityConfig.java
  src/main/java/com/example/mate/common/response/PageResponse.java
  src/main/java/com/example/mate/domain/goods/repository/GoodsPostRepository.java
  src/main/java/com/example/mate/domain/member/controller/ProfileController.java
  src/main/java/com/example/mate/domain/member/dto/response/MyGoodsRecordResponse.java
  src/main/java/com/example/mate/domain/member/service/FollowService.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
Labels: ✨ Feature, ✅ Test

#55 MATE-41 : [FEAT] : 회원 메이트 후기 페이징 조회 구현
  src/main/java/com/example/mate/domain/mate/repository/MateReviewRepositoryCustom.java
  src/main/java/com/example/mate/domain/mate/repository/MateReviewRepositoryImpl.java
  src/main/java/com/example/mate/domain/member/controller/ProfileController.java
  src/main/java/com/example/mate/domain/member/dto/response/MyReviewResponse.java
  src/main/java/com/example/mate/domain/member/dto/response/MyVisitResponse.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
Labels: ✨ Feature, ✅ Test

#52 MATE-52: [FEAT] 굿즈거래 후기 등록 기능 구현
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/common/response/PageResponse.java
  src/main/java/com/example/mate/domain/constant/Rating.java
  src/main/java/com/example/mate/domain/goods/controller/GoodsController.java
  src/main/java/com/example/mate/domain/goods/dto/request/GoodsReviewFormRequest.java
  src/main/java/com/example/mate/domain/goods/dto/request/GoodsReviewRequest.java
  src/main/java/com/example/mate/domain/goods/dto/response/GoodsPostSummaryResponse.java
  src/main/java/com/example/mate/domain/goods/dto/response/GoodsReviewFormResponse.java
  src/main/java/com/example/mate/domain/goods/dto/response/GoodsReviewResponse.java
  src/main/java/com/example/mate/domain/goods/entity/GoodsPost.java
  src/main/java/com/example/mate/domain/goods/entity/GoodsPostImage.java
  src/main/java/com/example/mate/domain/goods/entity/GoodsReview.java
  src/main/java/com/example/mate/domain/goods/repository/GoodsReviewRepository.java
  src/main/java/com/example/mate/domain/goods/service/GoodsService.java
  src/test/java/com/example/mate/domain/goods/controller/GoodsControllerTest.java
  src/test/java/com/example/mate/domain/goods/integration/GoodsIntegrationTest.java
  src/test/java/com/example/mate/domain/goods/service/GoodsServiceTest.java
Labels: ✨ Feature, ✅ Test

#53 MATE-57 : [FEAT] 경기정보 및 순위 크롤링 기능 및 스케쥴러 구현
  build.gradle
  http/Crawler.http
  src/main/java/com/example/mate/MateApplication.java
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/constant/StadiumInfo.java
  src/main/java/com/example/mate/domain/constant/TeamInfo.java
  src/main/java/com/example/mate/domain/crawler/config/SchedulingConfig.java
  src/main/java/com/example/mate/domain/crawler/config/WebDriverConfig.java
  src/main/java/com/example/mate/domain/crawler/constant/CrawlingStatusType.java
  src/main/java/com/example/mate/domain/crawler/constant/GameType.java
  src/main/java/com/example/mate/domain/crawler/controller/CrawlingController.java
  src/main/java/com/example/mate/domain/crawler/dto/CrawlingStatus.java
  src/main/java/com/example/mate/domain/crawler/dto/CrawlingStatusResponse.java
  src/main/java/com/example/mate/domain/crawler/scheduler/CrawlingScheduler.java
  src/main/java/com/example/mate/domain/crawler/service/CrawlingService.java
  src/main/java/com/example/mate/domain/match/dto/response/TeamResponse.java
  src/main/java/com/example/mate/domain/match/entity/Match.java
  src/main/java/com/example/mate/domain/match/entity/TeamRecord.java
  src/main/java/com/example/mate/domain/match/repository/MatchRepository.java
  src/main/java/com/example/mate/domain/match/repository/TeamRecordRepository.java
  src/main/java/com/example/mate/domain/match/service/TeamService.java
  src/main/resources/application-common.yml
Labels: ✨ Feature

#56 MATE-58 : [FEAT] 날씨 API 기능 구현
  src/main/java/com/example/mate/MateApplication.java
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/common/response/PageResponse.java
  src/main/java/com/example/mate/domain/match/api/WeatherApiClient.java
  src/main/java/com/example/mate/domain/match/dto/response/WeatherApiResponse.java
  src/main/java/com/example/mate/domain/match/entity/Weather.java
  src/main/java/com/example/mate/domain/match/repository/MatchRepository.java
  src/main/java/com/example/mate/domain/match/service/WeatherService.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#57 MATE-58 : [FIX] Revert 날씨 API 기능 구현 (#56)
  src/main/java/com/example/mate/MateApplication.java
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/common/response/PageResponse.java
  src/main/java/com/example/mate/domain/match/api/WeatherApiClient.java
  src/main/java/com/example/mate/domain/match/dto/response/WeatherApiResponse.java
  src/main/java/com/example/mate/domain/match/entity/Weather.java
  src/main/java/com/example/mate/domain/match/repository/MatchRepository.java
  src/main/java/com/example/mate/domain/match/service/WeatherService.java
  src/test/java/com/example/mate/domain/match/controller/TeamControllerTest.java
  src/test/java/com/example/mate/domain/match/integration/TeamRecordIntegrationTest.java
  src/test/java/com/example/mate/domain/match/service/TeamServiceTest.java
  src/test/resources/application-test.yml
Labels: 🐞 BugFix

#58 MATE-70 : [FEAT] 날씨 API 기능 재구현
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/match/api/WeatherApiClient.java
  src/main/java/com/example/mate/domain/match/dto/response/WeatherApiResponse.java
  src/main/java/com/example/mate/domain/match/entity/Weather.java
  src/main/java/com/example/mate/domain/match/repository/MatchRepository.java
  src/main/java/com/example/mate/domain/match/service/WeatherService.java
Labels: ✨ Feature

#60 MATE-40 : [FEAT] 프로필 굿즈거래 후기 페이징 조회 구현
  src/main/java/com/example/mate/domain/goods/repository/GoodsReviewRepositoryCustom.java
  src/main/java/com/example/mate/domain/goods/repository/GoodsReviewRepositoryImpl.java
  src/main/java/com/example/mate/domain/member/controller/ProfileController.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
Labels: ✨ Feature, ✅ Test

#62 MATE-65 : [FEAT] 메이트 게시글 수정, 삭제 제약조건 추가
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/mate/controller/MateController.java
  src/main/java/com/example/mate/domain/mate/dto/request/MatePostStatusRequest.java
  src/main/java/com/example/mate/domain/mate/entity/Visit.java
  src/main/java/com/example/mate/domain/mate/service/MateService.java
  src/test/java/com/example/mate/domain/mate/controller/MateControllerTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateStatusControllerTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateStatusIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/service/MateServiceTest.java
  src/test/java/com/example/mate/domain/mate/service/MateStatusServiceTest.java
Labels: ✨ Feature, ✅ Test

#59 MATE-68: [FEAT] GoodsController 클래스에 Swagger 작성
  src/main/java/com/example/mate/domain/goods/controller/GoodsController.java
Labels: 📃 Docs, ✨ Feature

#67 MATE-75 : [FEAT] 메이트 상세보기 반환값에 matchId 추가
  src/main/java/com/example/mate/domain/mate/dto/response/MatePostDetailResponse.java
Labels: ✨ Feature

#63 MATE-72 : [FEAT] 경기 전적 조회 수정
  src/main/java/com/example/mate/domain/match/repository/MatchRepository.java
  src/main/java/com/example/mate/domain/match/service/MatchService.java
  src/main/java/com/example/mate/domain/match/service/WeatherService.java
  src/test/java/com/example/mate/domain/match/controller/MatchControllerTest.java
  src/test/java/com/example/mate/domain/match/integration/MatchIntegrationTest.java
  src/test/java/com/example/mate/domain/match/service/MatchServiceTest.java
Labels: ✨ Feature

#65 MATE-67 : [FEAT] MateController 클래스에 Swagger 작성
  src/main/java/com/example/mate/domain/mate/controller/MateController.java
Labels: 📃 Docs

#64 MATE-73: [FEAT] 굿즈거래 채팅방 생성 기능 구현
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/goods/controller/GoodsChatController.java
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatController.java
  src/main/java/com/example/mate/domain/goodsChat/dto/response/GoodsChatRoomResponse.java
  src/main/java/com/example/mate/domain/goodsChat/entity/GoodsChatMessage.java
  src/main/java/com/example/mate/domain/goodsChat/entity/GoodsChatPart.java
  src/main/java/com/example/mate/domain/goodsChat/entity/GoodsChatPartId.java
  src/main/java/com/example/mate/domain/goodsChat/entity/GoodsChatRoom.java
  src/main/java/com/example/mate/domain/goodsChat/repository/GoodsChatRoomRepository.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatService.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatControllerTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatServiceTest.java
Labels: ✨ Feature, ✅ Test

#66 MATE-42 : [FEAT] 프로필 직관 타임라인 페이징 조회 구현
  src/main/java/com/example/mate/domain/goods/repository/GoodsReviewRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/mate/repository/MateRepository.java
  src/main/java/com/example/mate/domain/mate/repository/MateReviewRepository.java
  src/main/java/com/example/mate/domain/mate/repository/MateReviewRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/mate/repository/VisitPartRepository.java
  src/main/java/com/example/mate/domain/member/controller/ProfileController.java
  src/main/java/com/example/mate/domain/member/dto/response/MyTimelineResponse.java
  src/main/java/com/example/mate/domain/member/dto/response/MyVisitResponse.java
  src/main/java/com/example/mate/domain/member/repository/TimelineRepositoryCustom.java
  src/main/java/com/example/mate/domain/member/repository/TimelineRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
Labels: ✨ Feature, ✅ Test

#68 MATE-76 : [FEAT] 팀당 KBO 순위 조회 기능 구현
  http/Match.http
  src/main/java/com/example/mate/domain/constant/TeamInfo.java
  src/main/java/com/example/mate/domain/match/controller/TeamController.java
  src/main/java/com/example/mate/domain/match/dto/request/MatchRequest.java
  src/main/java/com/example/mate/domain/match/dto/request/StadiumRequest.java
  src/main/java/com/example/mate/domain/match/dto/request/TeamRequest.java
  src/main/java/com/example/mate/domain/match/dto/request/WeatherRequest.java
  src/main/java/com/example/mate/domain/match/service/TeamService.java
  src/test/java/com/example/mate/domain/match/controller/TeamControllerTest.java
  src/test/java/com/example/mate/domain/match/integration/TeamRecordIntegrationTest.java
  src/test/java/com/example/mate/domain/match/service/TeamServiceTest.java
Labels: ✨ Feature, ✅ Test

#69 MATE-74 : [FEAT] WebSocket 설정 및 채팅 인프라 구축
  build.gradle
  src/main/java/com/example/mate/common/config/WebSocketConfig.java
  src/main/java/com/example/mate/domain/mateChat/entity/MateChatMessage.java
  src/main/java/com/example/mate/domain/mateChat/entity/MateChatRoom.java
  src/main/java/com/example/mate/domain/mateChat/entity/MateChatRoomMember.java
  src/main/java/com/example/mate/domain/mateChat/message/MessageType.java
Labels: ✨ Feature

#35 MATE-61 : [!HOTFIX] JWT Token 기능과 Spring Security 설정으로 인한 컨트롤러 테스트 빈 등록 문제 해결
  http/Member.http
  src/main/java/com/example/mate/common/config/SecurityConfig.java
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/common/error/GlobalExceptionHandler.java
  src/main/java/com/example/mate/common/security/auth/CustomUserPrincipal.java
  src/main/java/com/example/mate/common/security/filter/JwtCheckFilter.java
  src/main/java/com/example/mate/common/security/util/JwtUtil.java
  src/main/java/com/example/mate/domain/member/controller/MemberController.java
  src/main/java/com/example/mate/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/com/example/mate/domain/member/entity/Member.java
  src/main/java/com/example/mate/domain/member/entity/Role.java
  src/main/java/com/example/mate/domain/member/repository/MemberRepository.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/test/java/com/example/mate/MateApplicationTests.java
  src/test/java/com/example/mate/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/mate/domain/goods/controller/GoodsControllerTest.java
  src/test/java/com/example/mate/domain/goods/integration/GoodsIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatControllerTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/match/controller/MatchControllerTest.java
  src/test/java/com/example/mate/domain/match/controller/TeamControllerTest.java
  src/test/java/com/example/mate/domain/match/integration/MatchIntegrationTest.java
  src/test/java/com/example/mate/domain/match/integration/TeamRecordIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateControllerTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateReviewControllerTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateStatusControllerTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateStatusIntegrationTest.java
  src/test/java/com/example/mate/domain/member/controller/FollowControllerTest.java
  src/test/java/com/example/mate/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/FollowIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
Labels: 🐞 BugFix, ✨ Feature, ✅ Test

#71 MATE-82 : [FEAT] 깃허브 액션을 사용한 CI/CD 구축
  .github/workflows/deploy.yml
  .gitignore
  src/main/resources/application.yml
Labels: ✨ Feature, ⚙ Setting

#73 MATE-83 : [FEAT] 테스트 코드 @MockBean jwtUtil 추가
  src/test/java/com/example/mate/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/mate/domain/auth/integration/NaverAuthIntegrationTest.java
  src/test/java/com/example/mate/domain/goods/integration/GoodsIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatControllerTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/match/integration/MatchIntegrationTest.java
  src/test/java/com/example/mate/domain/match/integration/TeamRecordIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateControllerTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateStatusIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/FollowIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
Labels: 🐞 BugFix, ✨ Feature

#74 MATE-84 : [FIX] yml 파일 변경
  .github/workflows/deploy.yml
  src/main/resources/application-common.yml
Labels: 🔨 Refactor, ⚙ Setting

#78 MATE-86 : [FEAT] 토큰 발급을 위한 로그인 기능 추가 및 회원 URI 수정
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/auth/controller/AuthController.java
  src/main/java/com/example/mate/domain/auth/service/NaverAuthService.java
  src/main/java/com/example/mate/domain/crawler/scheduler/CrawlingScheduler.java
  src/main/java/com/example/mate/domain/member/controller/FollowController.java
  src/main/java/com/example/mate/domain/member/controller/MemberController.java
  src/main/java/com/example/mate/domain/member/controller/ProfileController.java
  src/main/java/com/example/mate/domain/member/dto/request/MemberInfoUpdateRequest.java
  src/main/java/com/example/mate/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/main/resources/application-common.yml
  src/test/java/com/example/mate/config/WithAuthMember.java
  src/test/java/com/example/mate/config/WithAuthMemberSecurityContextFactory.java
  src/test/java/com/example/mate/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/mate/domain/auth/integration/NaverAuthIntegrationTest.java
  src/test/java/com/example/mate/domain/auth/service/NaverAuthServiceTest.java
  src/test/java/com/example/mate/domain/member/controller/FollowControllerTest.java
  src/test/java/com/example/mate/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/FollowIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
Labels: ✨ Feature, 🔨 Refactor, ⚙ Setting, ✅ Test

#79 MATE-87 : [FIX] 크롤링 스케쥴러 테스트 주석 변경
  src/main/java/com/example/mate/domain/crawler/scheduler/CrawlingScheduler.java
Labels: ⚙ Setting

#80 MATE-87-1 : [FIX] deploy.yml 변경
  .github/workflows/deploy.yml
Labels: 🐞 BugFix

#81 MATE-87-2 : [FIX] deploy.yml 변경
  .github/workflows/deploy.yml
Labels: 🐞 BugFix

#82 MATE-86 : [FEAT] 메인 페이지 조회 기능 인증 제외 설정
  src/main/java/com/example/mate/common/security/filter/JwtCheckFilter.java
Labels: ✨ Feature

#83 MATE-89 : [FIX] KT 팀 이름 변경으로 인한 파싱 에러 해결
  src/main/java/com/example/mate/domain/crawler/controller/CrawlingController.java
  src/main/java/com/example/mate/domain/crawler/service/CrawlingService.java
Labels: 🐞 BugFix

#84 MATE-91 : [FEAT] 메이트 게시글 상세 조회 반환값 수정
  src/main/java/com/example/mate/domain/mate/dto/response/MatePostDetailResponse.java
  src/test/java/com/example/mate/domain/mate/controller/MateControllerTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/service/MateServiceTest.java
  src/test/java/com/example/mate/domain/member/integration/FollowIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
Labels: ✨ Feature

#85 MATE-93 : [FIX] 회원 타임라인 페이지 번호 문제 해결 matePostId 반환 추가
  src/main/java/com/example/mate/domain/match/entity/Match.java
  src/main/java/com/example/mate/domain/mate/entity/MateReview.java
  src/main/java/com/example/mate/domain/member/dto/response/MyVisitResponse.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
Labels: 🐞 BugFix, ✨ Feature, ✅ Test

#86 MATE-94 : [REFACTOR] 굿즈거래 채팅방 입장 기능 리팩토링
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatMessageController.java
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomController.java
  src/main/java/com/example/mate/domain/goodsChat/dto/request/GoodsChatMessageRequest.java
  src/main/java/com/example/mate/domain/goodsChat/dto/response/GoodsChatRoomResponse.java
  src/main/java/com/example/mate/domain/goodsChat/repository/GoodsChatMessageRepository.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatMessageService.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatService.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomControllerTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatServiceTest.java
Labels: 🔨 Refactor

#88 MATE-98 : [FIX] SwaggerConfig 클래스 포트번호 변경
  src/main/java/com/example/mate/common/config/SwaggerConfig.java
Labels: 🐞 BugFix

#89 MATE-98 : [FIX] Jwt 기반 시큐리티 설정 변경
  src/main/java/com/example/mate/common/security/filter/JwtCheckFilter.java
Labels: 🐞 BugFix

#91 MATE-100 : [FEAT] 스크립트 수정
  .github/workflows/deploy.yml
  scripts/start-server.sh
Labels: ✨ Feature

#93 MATE-102 : [FEAT] 메이트 채팅방 제약 기능 추가
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/mate/repository/VisitPartRepository.java
  src/main/java/com/example/mate/domain/mateChat/service/MateChatRoomService.java
Labels: ✨ Feature

#94 MATE-105 : [FEAT] 메이트 채팅방 매핑 url 변경
  src/main/java/com/example/mate/domain/mateChat/controller/MateChatRoomController.java
Labels: ✨ Feature

#92 MATE-90 : [FEAT] S3 연결 및 파일(이미지) 관리 서비스 구현
  build.gradle
  src/main/java/com/example/mate/common/config/S3Config.java
  src/main/java/com/example/mate/common/utils/file/FileUploader.java
  src/main/java/com/example/mate/domain/file/FileService.java
  src/main/java/com/example/mate/domain/file/FileValidator.java
  src/main/java/com/example/mate/domain/goods/controller/GoodsController.java
  src/main/java/com/example/mate/domain/goods/dto/request/GoodsPostRequest.java
  src/main/java/com/example/mate/domain/goods/service/GoodsService.java
  src/main/java/com/example/mate/domain/mate/controller/MateController.java
  src/main/java/com/example/mate/domain/mate/entity/MatePost.java
  src/main/java/com/example/mate/domain/mate/service/MateService.java
  src/main/java/com/example/mate/domain/member/controller/MemberController.java
  src/main/java/com/example/mate/domain/member/entity/Member.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/main/resources/application-common.yml
  src/test/java/com/example/mate/common/utils/file/FileUploaderTest.java
  src/test/java/com/example/mate/common/utils/file/FileValidatorTest.java
  src/test/java/com/example/mate/domain/goods/service/GoodsServiceTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/service/MateServiceTest.java
  src/test/java/com/example/mate/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ⚙ Setting, ✅ Test

#95 MATE-106 : [CHORE] 자동 배포를 위해 deploy.yml 파일 수정
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, ⚙ Setting

#97 MATE-108 : [FIX] 웹소켓 인증 오류 해결
  src/main/java/com/example/mate/common/security/filter/JwtCheckFilter.java
Labels: 🐞 BugFix, 🔨 Refactor

#98 MATE-110 : [FEAT] 자체 로그인 응답값에 회원 정보 추가
  src/main/java/com/example/mate/domain/member/dto/response/MemberLoginResponse.java
  src/test/java/com/example/mate/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature, ✅ Test

#99 MATE-101 : [TEST] 굿즈거래 채팅 관련 기능들 테스트 코드 작성
  src/main/java/com/example/mate/domain/goodsChat/dto/request/GoodsChatMessageRequest.java
  src/main/java/com/example/mate/domain/goodsChat/entity/GoodsChatMessage.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatMessageService.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomControllerTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatMessageServiceTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatServiceTest.java
Labels: ✅ Test

#101 MATE-109 : [FEAT] 메이트 채팅방 멤버 조회 기능
  src/main/java/com/example/mate/domain/mateChat/controller/MateChatRoomController.java
  src/main/java/com/example/mate/domain/mateChat/service/MateChatRoomService.java
Labels: ✨ Feature

#100 MATE-111 : [FEAT] 자체 서비스 로그아웃 기능 구현
  build.gradle
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/common/security/filter/JwtCheckFilter.java
  src/main/java/com/example/mate/domain/member/controller/MemberController.java
  src/main/java/com/example/mate/domain/member/service/LogoutRedisService.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomControllerTest.java
  src/test/java/com/example/mate/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/LogoutRedisServiceTest.java
Labels: ✨ Feature, ✅ Test

#104 MATE-115 : [FEAT] 굿즈거래 채팅 도메인 Swagger 문서 작성
  src/main/java/com/example/mate/common/config/SecurityConfig.java
  src/main/java/com/example/mate/common/config/SwaggerConfig.java
  src/main/java/com/example/mate/common/security/filter/JwtCheckFilter.java
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomController.java
Labels: 📃 Docs, ✨ Feature

#105 MATE-113 : [FEAT] 메이트 관련 기능 url에서 memberId 제거
  Dockerfile
  build.gradle
  src/main/java/com/example/mate/common/config/SecurityConfig.java
  src/main/java/com/example/mate/common/config/SwaggerConfig.java
  src/main/java/com/example/mate/common/config/WebMvcConfig.java
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/common/response/PageResponse.java
  src/main/java/com/example/mate/common/security/filter/JwtCheckFilter.java
  src/main/java/com/example/mate/common/utils/validator/EnumValidator.java
  src/main/java/com/example/mate/common/utils/validator/ValidEnum.java
  src/main/java/com/example/mate/common/validator/ValidPageable.java
  src/main/java/com/example/mate/common/validator/ValidPageableArgumentResolver.java
  src/main/java/com/example/mate/domain/goods/controller/GoodsController.java
  src/main/java/com/example/mate/domain/goods/dto/request/GoodsPostRequest.java
  src/main/java/com/example/mate/domain/goods/dto/request/GoodsReviewRequest.java
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomController.java
  src/main/java/com/example/mate/domain/mate/controller/MateController.java
  src/main/java/com/example/mate/domain/mate/dto/request/MatePostCreateRequest.java
  src/main/java/com/example/mate/domain/mate/dto/request/MatePostSearchRequest.java
  src/main/java/com/example/mate/domain/mate/dto/request/MatePostStatusRequest.java
  src/main/java/com/example/mate/domain/mate/dto/request/MatePostUpdateRequest.java
  src/main/java/com/example/mate/domain/mate/service/MateService.java
  src/main/java/com/example/mate/domain/mateChat/controller/MateChatRoomController.java
  src/main/java/com/example/mate/domain/member/controller/FollowController.java
  src/main/java/com/example/mate/domain/member/controller/MemberController.java
  src/main/java/com/example/mate/domain/member/controller/ProfileController.java
  src/main/java/com/example/mate/domain/member/service/FollowService.java
  src/main/java/com/example/mate/domain/member/service/LogoutRedisService.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
  src/test/java/com/example/mate/common/utils/file/FileValidatorTest.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomControllerTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateControllerTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateReviewControllerTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateStatusControllerTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateStatusIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/service/MateServiceTest.java
  src/test/java/com/example/mate/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/LogoutRedisServiceTest.java
Labels: ✨ Feature, ✅ Test

#108 MATE-118 : [FEAT] 메이트 관련 기능 url에서 memberId 제거
  src/main/java/com/example/mate/domain/mate/controller/MateController.java
  src/main/java/com/example/mate/domain/mate/dto/request/MatePostCreateRequest.java
  src/main/java/com/example/mate/domain/mate/service/MateService.java
  src/test/java/com/example/mate/domain/mate/controller/MateControllerTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateReviewControllerTest.java
  src/test/java/com/example/mate/domain/mate/controller/MateStatusControllerTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateStatusIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/service/MateServiceTest.java
  src/test/java/com/example/mate/domain/mate/service/MateStatusServiceTest.java
Labels: ✨ Feature, ✅ Test

#110 MATE-120 : [FEAT] ValidPageableArgumentResolver 클래스 수정
  src/main/java/com/example/mate/common/validator/ValidPageableArgumentResolver.java
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomController.java
  src/main/java/com/example/mate/domain/mateChat/controller/MateChatRoomController.java
Labels: ✨ Feature

#111 MATE-121 : [FEAT] 메이트 상세조회 api에 현재 채팅방 인원값 추가
  src/main/java/com/example/mate/domain/mate/dto/response/MatePostDetailResponse.java
  src/main/java/com/example/mate/domain/mate/service/MateService.java
  src/test/java/com/example/mate/domain/mate/service/MateServiceTest.java
Labels: ✨ Feature

#109 MATE-119 : [REFACTOR] 굿즈거래 대표사진 반환 로직 리팩토링
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/common/validator/ValidPageableArgumentResolver.java
  src/main/java/com/example/mate/domain/goods/dto/request/GoodsPostRequest.java
  src/main/java/com/example/mate/domain/goods/dto/response/GoodsPostResponse.java
  src/main/java/com/example/mate/domain/goods/dto/response/LocationInfo.java
  src/main/java/com/example/mate/domain/goods/dto/response/MemberInfo.java
  src/main/java/com/example/mate/domain/goods/entity/GoodsPost.java
  src/main/java/com/example/mate/domain/goods/entity/GoodsPostImage.java
  src/main/java/com/example/mate/domain/goods/repository/GoodsPostRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/goods/repository/GoodsReviewRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/goods/service/GoodsService.java
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomController.java
  src/test/java/com/example/mate/domain/goods/controller/GoodsControllerTest.java
  src/test/java/com/example/mate/domain/goods/entity/GoodsPostTest.java
  src/test/java/com/example/mate/domain/goods/integration/GoodsIntegrationTest.java
  src/test/java/com/example/mate/domain/goods/service/GoodsServiceTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
Labels: 🔨 Refactor

#112 MATE-103 : [REFACTOR] 회원 프로필 타임라인 조회 성능 개선
  src/main/java/com/example/mate/domain/match/entity/Match.java
  src/main/java/com/example/mate/domain/match/repository/MatchRepository.java
  src/main/java/com/example/mate/domain/mate/repository/MateRepository.java
  src/main/java/com/example/mate/domain/mate/repository/MateReviewRepository.java
  src/main/java/com/example/mate/domain/mate/repository/VisitPartRepository.java
  src/main/java/com/example/mate/domain/mate/repository/VisitRepository.java
  src/main/java/com/example/mate/domain/member/repository/TimelineRepositoryCustom.java
  src/main/java/com/example/mate/domain/member/repository/TimelineRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#114 MATE-124 : [FEAT] 경기 정보 조회 (마이팀 선택 - 상단 배너용) 인증 제외 추가
  src/main/java/com/example/mate/common/security/filter/JwtCheckFilter.java
Labels: ✨ Feature

#115 MATE-125 : [FEAT] S3 정적 호스팅 페이지 CORS 연결 허용 설정
  src/main/java/com/example/mate/common/config/SecurityConfig.java
Labels: 🐞 BugFix

#116 MATE-127 : [REFACTOR] CATCH Mi 로그아웃 및 JWT 로직 리팩토링
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/common/security/util/JwtUtil.java
  src/main/java/com/example/mate/domain/member/controller/MemberController.java
  src/main/java/com/example/mate/domain/member/service/LogoutRedisService.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/test/java/com/example/mate/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/LogoutRedisServiceTest.java
  src/test/java/com/example/mate/domain/member/service/MemberServiceTest.java
Labels: 🔨 Refactor

#118 MATE-129 : [FEAT] 배포환경에서의 크롤링 테스트를 위한 스케쥴러 시간 조정
  src/main/java/com/example/mate/domain/crawler/controller/CrawlingController.java
  src/main/java/com/example/mate/domain/crawler/scheduler/CrawlingScheduler.java
  src/main/java/com/example/mate/domain/crawler/service/CrawlingService.java
  src/test/java/com/example/mate/MateApplicationTests.java
  src/test/java/com/example/mate/domain/auth/integration/NaverAuthIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsPost/integration/GoodsPostIntegrationTest.java
  src/test/java/com/example/mate/domain/match/integration/MatchIntegrationTest.java
  src/test/java/com/example/mate/domain/match/integration/TeamRecordIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateStatusIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/FollowIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
Labels: 🔨 Refactor
