Repository prgrms-web-devcourse-final-project/WEB1_2_PitchingMate_BE, pull requests merged in 2025-01, with the labels that each got.

#119 Mate-135 : [FEAT] 마이페이지 작성글 페이징 조회 기능 구현
  src/main/java/com/example/mate/domain/goodsPost/repository/GoodsPostRepository.java
  src/main/java/com/example/mate/domain/mate/repository/MateRepository.java
  src/main/java/com/example/mate/domain/member/controller/ProfileController.java
  src/main/java/com/example/mate/domain/member/service/ProfileService.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
Labels: ✨ Feature, ✅ Test

#120 MATE-140 : 연도가 바뀌어 오류났던 자체 회원 가입 테스트 코드 수정
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
Labels: 🔨 Refactor, ✅ Test

#121 MATE-139 : [FEAT] 도커파일에 크롬 및 크롬드라이버 설치
  .github/workflows/deploy.yml
  Dockerfile
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
Labels: ✨ Feature

#122 MATE-141 : [FEAT] 도커파일에 환경변수 전달
  appspec.yml
  scripts/start-server.sh
Labels: ✨ Feature

#125 MATE-142 : [FEAT] 도커 파일 내 크롬 및 크롬 드라이버 설정
  Dockerfile
  src/main/java/com/example/mate/domain/crawler/config/WebDriverConfig.java
Labels: ✨ Feature

#126 MATE-143 : [!HOTFIX] Dockerfile 내 문법오류 수정
  Dockerfile
Labels: 🐞 BugFix

#123 MATE-132 : [FEAT] 썸네일 이미지 생성 및 저장, 삭제 기능 구현
  build.gradle
  src/main/java/com/example/mate/domain/file/FileService.java
  src/main/java/com/example/mate/domain/file/FileUtils.java
  src/main/java/com/example/mate/domain/goodsChat/dto/response/GoodsChatMessageResponse.java
  src/main/java/com/example/mate/domain/goodsChat/dto/response/GoodsChatRoomResponse.java
  src/main/java/com/example/mate/domain/goodsChat/dto/response/GoodsChatRoomSummaryResponse.java
  src/main/java/com/example/mate/domain/goodsPost/dto/response/GoodsPostResponse.java
  src/main/java/com/example/mate/domain/goodsPost/dto/response/GoodsPostSummaryResponse.java
  src/main/java/com/example/mate/domain/goodsPost/dto/response/MemberInfo.java
  src/main/java/com/example/mate/domain/goodsPost/service/GoodsPostService.java
  src/main/java/com/example/mate/domain/mate/dto/response/MatePostDetailResponse.java
  src/main/java/com/example/mate/domain/mate/dto/response/MatePostSummaryResponse.java
  src/main/java/com/example/mate/domain/mate/service/MateService.java
  src/main/java/com/example/mate/domain/mateChat/dto/response/MateChatMessageResponse.java
  src/main/java/com/example/mate/domain/mateChat/dto/response/MateChatRoomListResponse.java
  src/main/java/com/example/mate/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/example/mate/domain/member/dto/response/MemberSummaryResponse.java
  src/main/java/com/example/mate/domain/member/dto/response/MyGoodsRecordResponse.java
  src/main/java/com/example/mate/domain/member/dto/response/MyProfileResponse.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatServiceTest.java
  src/test/java/com/example/mate/domain/goodsPost/integration/GoodsPostIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsPost/service/GoodsPostServiceTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/service/MateServiceTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/ProfileServiceTest.java
  src/test/resources/test_photo.png
Labels: ✨ Feature, 🔨 Refactor

#124 MATE-134 : [FEAT] 회원 탈퇴 기능을 Soft Delete 방식으로 수정
  src/main/java/com/example/mate/domain/goodsPost/repository/GoodsPostRepository.java
  src/main/java/com/example/mate/domain/goodsPost/repository/GoodsPostRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/mate/repository/MateRepository.java
  src/main/java/com/example/mate/domain/mate/repository/MateRepositoryImpl.java
  src/main/java/com/example/mate/domain/member/entity/Member.java
  src/main/java/com/example/mate/domain/member/repository/MemberRepository.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/test/java/com/example/mate/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#127 MATE-130 : [FEAT] 메이트 채팅방 입/퇴장 이벤트 기능 구현 및 메이트 채팅 관련 테스트 코드 작성
  src/main/java/com/example/mate/domain/mateChat/event/MateChatEvent.java
  src/main/java/com/example/mate/domain/mateChat/event/MateChatEventHandler.java
  src/main/java/com/example/mate/domain/mateChat/event/MateChatEventPublisher.java
  src/main/java/com/example/mate/domain/mateChat/service/MateChatMessageService.java
  src/main/java/com/example/mate/domain/mateChat/service/MateChatRoomService.java
  src/test/java/com/example/mate/domain/mateChat/controller/MateChatControllerTest.java
  src/test/java/com/example/mate/domain/mateChat/service/MateChatMessageServiceTest.java
  src/test/java/com/example/mate/domain/mateChat/service/MateChatServiceTest.java
Labels: ✨ Feature, ✅ Test

#128 MATE-136 : [FEAT] 사용자 활동에 따른 매너 타율 업데이트 기능 구현
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/goodsPost/service/GoodsPostService.java
  src/main/java/com/example/mate/domain/goodsReview/service/GoodsReviewService.java
  src/main/java/com/example/mate/domain/mate/entity/Visit.java
  src/main/java/com/example/mate/domain/mate/repository/MateReviewRepository.java
  src/main/java/com/example/mate/domain/mate/service/MateService.java
  src/main/java/com/example/mate/domain/member/entity/ActivityType.java
  src/main/java/com/example/mate/domain/member/entity/Member.java
  src/test/java/com/example/mate/domain/goodsPost/integration/GoodsPostIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsPost/service/GoodsPostServiceTest.java
  src/test/java/com/example/mate/domain/goodsReview/integration/GoodsReviewIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsReview/service/GoodsReviewServiceTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/integration/MateStatusIntegrationTest.java
  src/test/java/com/example/mate/domain/mate/service/MateReviewServiceTest.java
  src/test/java/com/example/mate/domain/mate/service/MateServiceTest.java
  src/test/java/com/example/mate/domain/mate/service/MateStatusServiceTest.java
Labels: ✨ Feature, ✅ Test

#129 MATE-144 : [FIX] 배너 경기 데이터 조회 수정
  http/Match.http
  src/main/java/com/example/mate/domain/crawler/service/CrawlingService.java
  src/main/java/com/example/mate/domain/match/repository/MatchRepository.java
  src/main/java/com/example/mate/domain/match/service/MatchService.java
  src/test/java/com/example/mate/domain/match/integration/MatchIntegrationTest.java
  src/test/java/com/example/mate/domain/match/service/MatchServiceTest.java
Labels: 🐞 BugFix, ✅ Test

#130 MATE-146 : [FIX] 배너 경기 데이터 조회 SQL 수정
  src/main/java/com/example/mate/domain/match/repository/MatchRepository.java
  src/main/java/com/example/mate/domain/match/service/MatchService.java
  src/test/java/com/example/mate/domain/match/service/MatchServiceTest.java
Labels: 🐞 BugFix

#131 MATE-145 : [FEAT] MongoDB 의존성 추가 및 설정
  build.gradle
  src/main/java/com/example/mate/common/config/MongoConfig.java
Labels: ✨ Feature, ⚙ Setting

#133 MATE-149 : [!HOTFIX] 굿즈거래 판매글 이미지 수정 로직 오류 해결
  src/main/java/com/example/mate/domain/goodsPost/controller/GoodsPostController.java
  src/main/java/com/example/mate/domain/goodsPost/service/GoodsPostService.java
Labels: 🐞 BugFix

#134 MATE-147 : [FEAT] SSE 기반 알림 구독 및 보내기 기능 구현
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/goodsPost/event/GoodsPostEvent.java
  src/main/java/com/example/mate/domain/goodsPost/event/GoodsPostEventHandler.java
  src/main/java/com/example/mate/domain/goodsPost/event/GoodsPostEventPublisher.java
  src/main/java/com/example/mate/domain/goodsPost/service/GoodsPostService.java
  src/main/java/com/example/mate/domain/matePost/event/MatePostEvent.java
  src/main/java/com/example/mate/domain/matePost/event/MatePostEventHandler.java
  src/main/java/com/example/mate/domain/matePost/event/MatePostEventPublisher.java
  src/main/java/com/example/mate/domain/matePost/service/MatePostService.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/main/java/com/example/mate/domain/notification/controller/NotificationController.java
  src/main/java/com/example/mate/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/mate/domain/notification/entity/Notification.java
  src/main/java/com/example/mate/domain/notification/entity/NotificationType.java
  src/main/java/com/example/mate/domain/notification/repository/EmitterRepository.java
  src/main/java/com/example/mate/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/example/mate/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/mate/domain/notification/service/NotificationService.java
  src/test/java/com/example/mate/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/example/mate/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/com/example/mate/domain/notification/repository/EmitterRepositoryImplTest.java
  src/test/java/com/example/mate/domain/notification/service/NotificationServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#135 MATE-152 : [FIX] @Mock 의존성 주입으로 알림 통합 테스트 코드 작동 수정
  src/test/java/com/example/mate/domain/goodsPost/service/GoodsPostServiceTest.java
  src/test/java/com/example/mate/domain/matePost/service/MateStatusServiceTest.java
  src/test/java/com/example/mate/domain/member/service/MemberServiceTest.java
Labels: 🐞 BugFix, ✅ Test

#136 MATE-150 : [REFACTOR] 굿즈거래 채팅 엔티티 MongoDB로 마이그레이션
  build.gradle
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomController.java
  src/main/java/com/example/mate/domain/goodsChat/document/GoodsChatMessage.java
  src/main/java/com/example/mate/domain/goodsChat/dto/response/GoodsChatMessageResponse.java
  src/main/java/com/example/mate/domain/goodsChat/entity/GoodsChatMessage.java
  src/main/java/com/example/mate/domain/goodsChat/entity/GoodsChatPart.java
  src/main/java/com/example/mate/domain/goodsChat/repository/GoodsChatMessageRepository.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatMessageService.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatService.java
  src/test/java/com/example/mate/config/mongoConfig/AcceptanceTestWithMongo.java
  src/test/java/com/example/mate/config/mongoConfig/EnableMongoTestServer.java
  src/test/java/com/example/mate/config/mongoConfig/MongoTestServerConfig.java
  src/test/java/com/example/mate/config/securityConfig/WithAuthMember.java
  src/test/java/com/example/mate/config/securityConfig/WithAuthMemberSecurityContextFactory.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomControllerTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatMessageServiceTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatServiceTest.java
  src/test/java/com/example/mate/domain/goodsPost/controller/GoodsPostControllerTest.java
  src/test/java/com/example/mate/domain/goodsPost/integration/GoodsPostIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsReview/controller/GoodsReviewControllerTest.java
  src/test/java/com/example/mate/domain/goodsReview/integration/GoodsReviewIntegrationTest.java
  src/test/java/com/example/mate/domain/mateChat/controller/MateChatControllerTest.java
  src/test/java/com/example/mate/domain/matePost/controller/MatePostControllerTest.java
  src/test/java/com/example/mate/domain/matePost/controller/MateStatusControllerTest.java
  src/test/java/com/example/mate/domain/matePost/integration/MatePostIntegrationTest.java
  src/test/java/com/example/mate/domain/matePost/integration/MatePostStatusIntegrationTest.java
  src/test/java/com/example/mate/domain/mateReview/controller/MateReviewControllerTest.java
  src/test/java/com/example/mate/domain/mateReview/integration/MateReviewIntegrationTest.java
  src/test/java/com/example/mate/domain/member/controller/FollowControllerTest.java
  src/test/java/com/example/mate/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/mate/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/FollowIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/integration/ProfileIntegrationTest.java
  src/test/java/com/example/mate/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/example/mate/domain/notification/integration/NotificationIntegrationTest.java
Labels: ✨ Feature, 🔨 Refactor

#139 MATE-155 : [FEAT] 굿즈 거래완료 메시지 전송 기능 구현
  src/main/java/com/example/mate/domain/constant/MessageType.java
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomController.java
  src/main/java/com/example/mate/domain/goodsChat/event/GoodsChatEventHandler.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatMessageService.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatService.java
  src/main/java/com/example/mate/domain/goodsPost/controller/GoodsPostController.java
  src/main/java/com/example/mate/domain/goodsPost/service/GoodsPostService.java
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomControllerTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatServiceTest.java
  src/test/java/com/example/mate/domain/goodsPost/controller/GoodsPostControllerTest.java
  src/test/java/com/example/mate/domain/goodsPost/integration/GoodsPostIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsPost/service/GoodsPostServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#138 MATE-154 : [FEAT] 회원의 알림 페이징 조회 기능 구현
  src/main/java/com/example/mate/domain/notification/controller/NotificationController.java
  src/main/java/com/example/mate/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/mate/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/mate/domain/notification/service/NotificationService.java
  src/test/java/com/example/mate/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/example/mate/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/com/example/mate/domain/notification/service/NotificationServiceTest.java
Labels: ✨ Feature, ✅ Test

#140 MATE-157 : [FEAT] 알림 읽음 처리 기능 구현 및 알림 엔티티 수정
  src/main/java/com/example/mate/common/error/ErrorCode.java
  src/main/java/com/example/mate/domain/notification/controller/NotificationController.java
  src/main/java/com/example/mate/domain/notification/entity/Notification.java
  src/main/java/com/example/mate/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/mate/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/example/mate/domain/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/notification/service/NotificationService.java
  src/test/java/com/example/mate/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/example/mate/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/com/example/mate/domain/notification/service/NotificationServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#141 MATE-151 : [FEAT] 메이트 채팅 저장소를 MySQL에서 MongoDB로 마이그레이션
  src/main/java/com/example/mate/domain/mateChat/document/MateChatMessage.java
  src/main/java/com/example/mate/domain/mateChat/dto/request/MateChatMessageRequest.java
  src/main/java/com/example/mate/domain/mateChat/dto/response/MateChatMessageResponse.java
  src/main/java/com/example/mate/domain/mateChat/entity/MateChatMessage.java
  src/main/java/com/example/mate/domain/mateChat/event/MateChatEvent.java
  src/main/java/com/example/mate/domain/mateChat/repository/MateChatMessageRepository.java
  src/main/java/com/example/mate/domain/mateChat/service/MateChatMessageService.java
  src/main/java/com/example/mate/domain/mateChat/service/MateChatRoomService.java
  src/main/resources/static/chat/index.html
  src/test/java/com/example/mate/domain/mateChat/controller/MateChatControllerTest.java
  src/test/java/com/example/mate/domain/mateChat/service/MateChatMessageServiceTest.java
  src/test/java/com/example/mate/domain/mateChat/service/MateChatServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#142 MATE-148 : [FEAT] Spring Batch 적용
  build.gradle
  src/main/java/com/example/mate/domain/batch/config/BatchConfiguration.java
  src/main/java/com/example/mate/domain/batch/config/QuartzConfiguration.java
  src/main/java/com/example/mate/domain/batch/job/CrawlingQuartzJob.java
  src/main/java/com/example/mate/domain/batch/step/processor/CrawlingReader.java
  src/main/java/com/example/mate/domain/batch/step/reader/CrawlingProcessor.java
  src/main/java/com/example/mate/domain/batch/step/writer/CrawlingWriter.java
  src/main/java/com/example/mate/domain/crawler/scheduler/CrawlingScheduler.java
Labels: ✨ Feature

#143 MATE-159 : [FEAT] 회원정보 조회 및 팔로우 관련 응답 필드 수정
  src/main/java/com/example/mate/domain/member/controller/MemberController.java
  src/main/java/com/example/mate/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/example/mate/domain/member/dto/response/MemberSummaryResponse.java
  src/main/java/com/example/mate/domain/member/service/MemberService.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatServiceTest.java
  src/test/java/com/example/mate/domain/mateChat/service/MateChatServiceTest.java
  src/test/java/com/example/mate/domain/member/controller/FollowControllerTest.java
  src/test/java/com/example/mate/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/mate/domain/member/integration/MemberIntegrationTest.java
  src/test/java/com/example/mate/domain/member/service/FollowServiceTest.java
  src/test/java/com/example/mate/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature, ✅ Test

#144 MATE-156 : [REFACTOR] 채팅내역 조회 기능을 No Offset 방식으로 변경
  src/main/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomController.java
  src/main/java/com/example/mate/domain/goodsChat/document/GoodsChatMessage.java
  src/main/java/com/example/mate/domain/goodsChat/dto/response/GoodsChatRoomResponse.java
  src/main/java/com/example/mate/domain/goodsChat/repository/GoodsChatMessageRepository.java
  src/main/java/com/example/mate/domain/goodsChat/repository/GoodsChatMessageRepositoryCustom.java
  src/main/java/com/example/mate/domain/goodsChat/repository/GoodsChatMessageRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/goodsChat/service/GoodsChatService.java
  src/main/resources/application-common.yml
  src/test/java/com/example/mate/domain/goodsChat/controller/GoodsChatRoomControllerTest.java
  src/test/java/com/example/mate/domain/goodsChat/integration/GoodsChatIntegrationTest.java
  src/test/java/com/example/mate/domain/goodsChat/service/GoodsChatServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#146 MATE-158 : [FEAT] 메이트 채팅내역 조회 기능을 No Offset 방식으로 변경
  src/main/java/com/example/mate/domain/mateChat/controller/MateChatRoomController.java
  src/main/java/com/example/mate/domain/mateChat/document/MateChatMessage.java
  src/main/java/com/example/mate/domain/mateChat/dto/response/MateChatRoomResponse.java
  src/main/java/com/example/mate/domain/mateChat/repository/MateChatMessageRepository.java
  src/main/java/com/example/mate/domain/mateChat/repository/MateChatMessageRepositoryCustom.java
  src/main/java/com/example/mate/domain/mateChat/repository/MateChatMessageRepositoryCustomImpl.java
  src/main/java/com/example/mate/domain/mateChat/service/MateChatRoomService.java
  src/test/java/com/example/mate/domain/mateChat/controller/MateChatControllerTest.java
  src/test/java/com/example/mate/domain/mateChat/service/MateChatServiceTest.java
Labels: ✨ Feature, ✅ Test
